# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4e90257a01e02524aa64b526cd224254"
name = "countdown-timer"
handle = "countdown-timer-99"
application_url = "https://winter-scotland-broker-online.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://winter-scotland-broker-online.trycloudflare.com/auth/callback", "https://winter-scotland-broker-online.trycloudflare.com/auth/shopify/callback", "https://winter-scotland-broker-online.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
