# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f227f8fe7a1324f320302512dd96c164"
name = "test"
handle = "test-19620"
application_url = "https://christina-ships-fibre-lions.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://christina-ships-fibre-lions.trycloudflare.com/auth/callback", "https://christina-ships-fibre-lions.trycloudflare.com/auth/shopify/callback", "https://christina-ships-fibre-lions.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
